### PR TITLE
CP-657 Setup code coverage through codecov.io

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- We need to report and display our code coverage.

## Changes
**Source:**
- n/a

**Tools:**
- Coverage tools updated
- travis.yml updated to run and report coverage to codecov.io

**Tests:**
- n/a

**Other:**
- Readme updated to include code coverage badge (will only work once this is merged into master)

## Areas of Regression
- n/a

## Testing
- Coverage badge should be visible on README (will report "unknown" coverage until merged)
- Travis-ci should pass and this output should be visible in the logs towards the bottom:

    ```
    The command "pub run dart_codecov_generator --report-on=lib/ --no-html --verbose" exited with 0.
    pub run dart_codecov coverage.lcov
    Running dart_codecov...
    Coverage sent to codecov.io successfully.
    ```

## Code Review
@trentgrover-wf
@maxwellpeterson-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified badge was working appropriately on readme, proper logging was in smithy build and coverage generation still worked as expected locally
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
