### PR TITLE
CP-882 Utilize dart_dev for tooling, fluri

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Dart_dev is public, we should use it and get rid of our tool scripts.

## Changes
**Source:**
- Remove old tool scripts (except docs)
- Configure and use dart_dev
- Update license headers to use `//` instead of `/*`

**Tests:**
- n/a

## Areas of Regression
- tooling

## Testing
- CI build passes and coverage is reported.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1, pending dart-dev release

**Comment by evanweible-wf** [comment]
@trentgrover-wf dart_dev has been published, CI passed

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
With these OSS repos, it may be a good idea to add a "#Development" section to the end of the README stating "This project uses dart_dev for tooling, check out the dart_dev docs for more information on how to use it" for 3rd parties

**Comment by evanweible-wf** [comment]
@maxwellpeterson-wf good idea, I'll open some issues

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that travis was still passing with new tooling
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
