### PR TITLE
CP-574 Release fluri 1.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-574

JIRA and PR's included in this release: 

 CP-583  - Fix fluri documentation generation  - https://github.com/Workiva/fluri/pull/9
 CP-587  - Ensure license texts are consistent.  - https://github.com/Workiva/fluri/pull/10
 CP-597  - fluri Dartfmt  - https://github.com/Workiva/fluri/pull/11
 CP-602  - Add Pub badge  - https://github.com/Workiva/fluri/pull/12
 CP-642  - Point travis-ci badge to master  - https://github.com/Workiva/fluri/pull/13
 CP-657  - Setup code coverage through codecov.io  - https://github.com/Workiva/fluri/pull/14
 CP-662  - Use dartanalyzer, fluri  - https://github.com/Workiva/fluri/pull/17
 CP-665  - Add changelog  - https://github.com/Workiva/fluri/pull/19

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.0.0...CP-574_release_1.0.1

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by travisreed-wf** [comment]
The new pubspec dependencies make me a little nervous. I am going to go talk to SOC real quick

**Comment by travisreed-wf** [comment]
RM +1 the team has received code reviews for the 3 new dependencies:

url: git://github.com/ekweible/coverage.git
url: git://github.com/ekweible/dart_codecov.git
url: git://github.com/ekweible/dart_codecov_generator.git

They are going to move this code over to a workiva owned repository going forward, but for now this is sufficient to satisfy SOC1 requirements

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
