### PR TITLE
CP-666 Update next release version, fluri 1.1.0

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Incorrect version in changelog for the next release, should be 1.1.0 according to semver

## Changes
- Changed 1.0.2 to 1.1.0 in changelog

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge (docs only)

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
