### PR TITLE
CP-1155 Update changelog with new methods/constructors

### PR DESCRIPTION
**Pull request by evanweible-wf**
**DOCS ONLY CHANGE**

Update changelog with new methods/constructors from #40 

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf (docs only change)

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
