### PR TITLE
CP-567 fluri Licenses

### PR DESCRIPTION
**Pull request by evanweible-wf**
Adds the necessary licenses to the repo:
- `lib/fluri.dart`
- `LICENSE`
- `NOTICE`

@trentgrover-wf @maxwellpeterson-wf

### CODE REVIEW

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Comment by jayudey-wf** [comment]
@rmconsole-wf

**Comment by rmconsole-wf** [comment]
- [x] All commits reviewed
- [x] QA Review
- [x] Security Review Completed if Applicable:  (N/A)

To remain in SOC1 Compliance the following users cannot merge this PR:
* evanweible-wf

		When this pull is merged I will use the following information:
		Version: fluri 1.0.0
		Release Ticket: CP-573

***
*Last updated on Tuesday, April 28 02:58 PM CST*

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
