### PR TITLE
CP-666 Release fluri 1.1.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-666

JIRA and PR's included in this release: 

 CP-687  - Small fixes, fluri  - https://github.com/Workiva/fluri/pull/24
 CP-697  - Add dartfmt check to CI build, fluri.  - https://github.com/Workiva/fluri/pull/27
 CP-704  - Update docs to use "fluri" var name  - https://github.com/Workiva/fluri/pull/29
 CP-816  - Update code coverage collection and reporting  - https://github.com/Workiva/fluri/pull/33
 CP-882  - Utilize dart_dev for tooling, fluri  - https://github.com/Workiva/fluri/pull/34
 CP-1153  - Improvements/additions appendToPath, addPathSegment, setQueryParam, from ctor, fromUri ctor  - https://github.com/Workiva/fluri/pull/40
 CP-1155  - Update changelog with new methods/constructors  - https://github.com/Workiva/fluri/pull/41
 CP-1170  - Update next release_version, fluri 1.1.0  - https://github.com/Workiva/fluri/pull/42
 CP-908  - Add "development" section to readme.  - https://github.com/Workiva/fluri/pull/36
 CP-932  - Move badges to separate line, fluri  - https://github.com/Workiva/fluri/pull/38

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.0.1...CP-666_release_1.1.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
