### PR TITLE
CP-2925 Documentation updates, add GH templates

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Changes

- Use release notes instead of changelog (link to releases page from changelog)
- Add versioning and stability commitment to readme
- Add GitHub issue template
- Add GitHub pull request template
- Add GitHub contributing guidelines

Also - shout out to the UIP team, I borrowed most of the contributing guidelines from their repos.

---

**Docs only change.**

@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
Smithy CI check will pass once this is merged: https://github.com/Workiva/fluri/pull/57

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
