### PR TITLE
CP-2924 Add smithy.yaml for dependency tracking

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
Need a smithy.yaml for RM dependency tracking.

@Workiva/client-platform-pp

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - smithy is now running
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
