### PR TITLE
CP-602 Add Pub badge

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Add pub padge

## Changes
**Source:**
- Add pub badge from shields.io to README

**Tests:**
- n/a

## Areas of Regression
- n/a

## Testing
- Pub badge displays latest pub release version and links to the pub package page for Fluri.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1 neat

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - badge is properly displayed in readme
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
