### PR TITLE
WP-4424 Release fluri 1.2.3

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [WP-4489 - Resolve dart_dev deprecation](https://github.com/Workiva/fluri/pull/65)
* [WP-4596 Update dependency ranges](https://github.com/Workiva/fluri/pull/66)

Requested by: @maxpeterson-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.2.2...version-bump-fluri-1-2-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.2.2...1.2.3

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
@Workiva/web-platform-pp

**Comment by evanweible-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
