### PR TITLE
CP-1242 Fix changelog formatting issue, fluri

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue
#44

doc-only change

## Code Review
@trentgrover-wf
@evanweible-wf 
@dustinlessard-wf
FYI @jayudey-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
