### PR TITLE
WP-4596 Update dependency ranges

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
### Issue:
1. Some of the dev need updated ranges to facilitate strong-mode consumption / DDC compilation.

### Solution
1. Update misc. dependencies to align with strong-mode / DDC compilation goals for the platform.

### Code Review

@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by toddbeckman-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Minimum dependency bump only
- [x] Dev +1's
- [x] CI passes
- [x] Dependency scan clean

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
