### PR TITLE
CP-597 fluri Dartfmt

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Dart code needs to be run through dartfmt to ensure consistent and clean code

## Changes
- Ran `dartfmt` on code
- Added `tool/dartfmt.sh` script

## Testing
- Travis should pass
- Running `./tool/dartfmt.sh` locally should not produce any changes to the code

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - ran formatting tool and no changes were identified
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
