### PR TITLE
CP-1246 Release fluri 1.2.0

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
- [CP-1772 Analyzer: enable strong mode and linter.](https://github.com/Workiva/fluri/pull/52)
- [CP-2817 Support multi-value parameters](https://github.com/Workiva/fluri/pull/53)

Requested by: evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.1.1...version-bump-fluri-1-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.1.1...1.2.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

for this release

**Pull request merged**
