### PR TITLE
CP-665 Add changelog

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- #16 
- We need a changelog file, especially since it's displayed on pub.dartlang.org

- Added `CHANGELOG.md`

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@jayudey-wf 

---

Don't merge this yet. I will keep this open until we're ready for the next release, at which point I'll finalize updates and get one last round of reviews. After that's merged and the release is cut, I'll reopen and repeat the process.

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge, docs only.

**Comment by jayudey-wf** [comment]
QA +1 doc change only

Merging into master

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
