### PR TITLE
CP-573 Release fluri 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-573

JIRA and PR's included in this release: 

 CP-572  - fluri Travis CI commit  - https://github.com/Workiva/fluri/pull/7
 CP-571  - Add client platform team to authors  - https://github.com/Workiva/fluri/pull/6
 CP-570  - Add authors, documentation, homepage to pubspec  - https://github.com/Workiva/fluri/pull/5
 CP-568  - Update Apache 2.0 License  - https://github.com/Workiva/fluri/pull/4
 CP-567  - fluri Licenses  - https://github.com/Workiva/fluri/pull/2
 CP-566  - Fluent URI library (fluri)  - https://github.com/Workiva/fluri/pull/1

Diff Between Last Tag and Proposed Release: N/A

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
## SOC 1 Checklist
- [ ] All commits reviewed (d5e741d7db03c2d9b67b07c14d4e46ad4ec39c19)
- [ ] QA Review
- [x] Security Review Completed if Applicable:  (N/A)

To remain in SOC1 Compliance the following users cannot merge this PR:
* jayudey-wf

		When this pull is merged I will use the following information:
		Version: fluri 1.0.0
		Release Ticket: CP-573

		This pull is considered the release of fluri 1.0.0. 
		The options defined for this repo will be carried out

***
*Last updated on Tuesday, April 28 03:00 PM CST*

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
