### PR TITLE
CP-587 Ensure license texts are consistent.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- The LICENSE and NOTICE files are currently inconsistent in their spacing.

## Changes
**Source:**
- Update the NOTICE to be consistent with LICENSE.

**Tests:**
- n/a

## Areas of Regression
- n/a

## Testing
- Travis-ci passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
## SOC 1 Checklist
- [ ] All commits reviewed (45869a160c8c7845eb2664728b4a7859a59db500)
- [ ] QA Review (may be done on the release of this version)
- [x] Security Review Completed if Applicable:  (N/A)

To remain in SOC1 Compliance the following users cannot merge this PR:
* evanweible-wf

		When this pull is merged I will not be able to function
		properly because no ticket is included in the title.
		If your team has decided not to use jira please indicate this in rmconsole

***
*Last updated on Tuesday, May 05 04:15 PM CST*

**Comment by trentgrover-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by jayudey-wf** [comment]
QA +1, update to license

merging into master

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Pull request merged**
