### PR TITLE
CP-1228 cleanup old scripts, fluri

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- remove old docs script
- add docs badge

## Changes
**Source:**
- none

**Tests:**
- none

## Areas of Regression
- doc generation

## Testing
- ensure doc gen works as expected

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
fixes https://github.com/Workiva/fluri/issues/45

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1 @jayudey-wf for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - doc generation is working as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
